mqtt:
  host: "broker.emqx.io" # must be specified. No defaults e.g.198.168.220.3 broker.emqx.io
  port: 1883 # Default value 1883 if not specified
  topic : "test/uns/#" # Default Topic is a wild card #. if required can be tuned to listen subset 
  qos: 1 # Default value is 1. Recommend 1 or 2. Do not use 0
  keep_alive: 60
  reconnect_on_failure : True
  version : 5 # Default is MQTTv5. Valid values are : 5 (for MQTTv5), 4 (for MQTTv311) , 3(for MQTTv31)
 #clean_session: false # specify this only if the protocol is not MQTTv5
  transport : "tcp"  # Default is tcp. Valid values are: websockets, tcp



historian:
  hostname: 'localhost'
# port: 5432  
  database: 'uns_historian'
  table: 'unifiednamespace'
  ignored_attributes : {}

dynaconf_merge: true
   